spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pizzeria2
    username: postgres
    password: pass
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    open-in-view: false
  messages:
    basename: messages
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 476821221223-7uh2tebbkpgjjvok8j6qtk4vsht51q7e.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: http://localhost:8080/login/oauth2/code/google
            scope:
              - openid
              - email
              - profile

app:
  image:
    bucket: C:\Users\KaMo User\IdeaProjects\maven-project2\images

springdoc:
  swagger-ui:
    oauth:
      client-id: 476821221223-7uh2tebbkpgjjvok8j6qtk4vsht51q7e.apps.googleusercontent.com
      client-secret: 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
      scopes: openid, email, profile
    oauth2-redirect-url: http://localhost:8080/swagger-ui/oauth2-redirect.html
